function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
	sound.play("#musique")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		print("Touch!")
		sound.play("/go#fx_tap")
		
		label.set_text("#tap", "tap and sound")
		timer.delay(0.5, false, function() label.set_text("#tap", "") end)
	end
end